spring:
  config:
    import: classpath:auth-prod.yml, classpath:aws.yml

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_DATABASE_URL}
    username: ${MYSQL_DATABASE_USERNAME}
    password: ${MYSQL_DATABASE_PASSWORD}

  sql:
    init:
      mode: always

  redis:
    host: ${PUBLIC_IP}
    port: 6379

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        format_sql: true

        jdbc:
          batch_size: 1000

    defer-datasource-initialization: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type.descriptor.sql: trace
